version = 0.1
[default.deploy.parameters]
stack_name = "whatsapp-processor"
resolve_s3 = true
s3_prefix = "whatsapp-processor"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "WhatsAppQueue=\"whatsapp-queue\""
